l=[10, 2, "odd",-1, 4.56, 3+5j, True, "even", 0]
print(l)
print(l[2])
print(l[3:5])
print(l*4)
print(len(l))   
l.append(100)
print (l)
l.remove("even")
print (l)
del(l[3])
print (l)
print(max(l))
print(min(l))
l.insert(2, 200)   
print (l)
l.sort()
print (l)   
#l.clear()